config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
namespace :admin do
    get '/' => 'homes#top'
    resources :items
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end

scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get '/customers/mypage' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    get '/customers/confirm_withdraw' => 'customers#confirm_withdraw'
    patch '/customers/information' => 'customers#update'
    patch '/customers/withdraw' => 'customers#withdraw'
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    get '/orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :index, :show, :create]
    post '/orders/confirm' => 'orders#confirm'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :profile_image
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  def with_tax_price
    (price * 1.1).floor
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def new
    @item = Item.new
  end

  def index
    @items = Item.page(params[:page])
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end

  def destroy

  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :profile_image)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
  <div class="row m-3">
    <div class="col offset-md-2">
      <h4>商品詳細</h4>
    </div>
  </div>

<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

  <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>
  <div class="form-group">
    <label for="image_image">商品画像</label>
    <%= f.file_field :profile_image, accept: "image/*", class: 'form-control-file' %>
  </div>
  <div class="form-group">
    <label for="item_name">商品名</label>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="item_introduction">商品説明</label>
    <%= f.text_area :introduction, class: 'form-control'%>
  </div>
  <div class="form-group">
    <label for="price">税抜価格</label>
    <%= f.text_field :price, class: 'form-control' %>
  </div>

  <div class="row justify-content-md-center">
    <div class="form-group">
      <%= f.submit "変更を保存する", class: "btn btn-success" %>
    </div>
  </div>

  <% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row m-3">
    <div class="col-6">
      <h4>商品一覧</h4>
    </div>
    <div class="col-4">
      <%= link_to  new_admin_item_path do %>
        <i class="fa-solid fa-plus"></i>
      <% end %>
    </div>
  </div>

  <table class="table">
    <thead class="table-dark">
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.name, admin_item_path(item.id) %></td>
        <td><%= item.price %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="row">
    <div class="mx-auto">
      <%= paginate @items%>
      </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="m-3">
  <div class="col offset-md-2">
    <h4>商品新規登録</h4>
  </div>
</div>

<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

  <%= form_with model: Item.new, url: admin_items_path, method: :post do |f| %>
  <div class="form-group">
    <label for="image_image">商品画像</label>
    <%= f.file_field :profile_image, accept: "image/*", class: 'form-control-file' %>
  </div>
  <div class="form-group">
    <label for="item_name">商品名</label>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="item_introduction">商品説明</label>
    <%= f.text_area :introduction, class: 'form-control'%>
  </div>
  <div class="form-group">
    <label for="price">税抜価格</label>
    <%= f.text_field :price, class: 'form-control' %>
  </div>

  <div class="row justify-content-md-center">
    <div class="form-group">
      <%= f.submit "新規登録", class: "btn btn-success" %>
    </div>
  </div>

  <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row m-3">
    <div class="col offset-md-2">
      <h4>商品詳細</h4>
    </div>
  </div>

  <div class="row">
    <div class="col-md-3">
      <div><%= image_tag @item.get_profile_image(100,100) %></div>
    </div>

    <div class="col-md-8 offset-md-1">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th scope="row">商品名</th>
            <td><%= @item.name %></td>
          </tr>
          <tr>
            <th scope="row">商品説明</th>
            <td><%= @item.introduction %></td>
           </tr>
           <tr>
            <th scope="row">税抜価格</th>
            <td ><%= @item.price %>円</td>
           </tr>
        </tbody>
      </table>
    </div>
  </div>

   <div class="row justify-content-md-center">
    <div class="form-group">
      <%= link_to "編集する", edit_admin_item_path(@item), class:"btn btn-sm btn-success" %>
    </div>
  </div>

</div>