config/routes.rb
Rails.application.routes.draw do
# 顧客用
# URL /customers/sign_in ...
devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
namespace :admin do
    get '/' => 'homes#top'
    resources :items
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show]
  end

scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'
    get '/customers/mypage' => 'customers#show'
    get '/customers/information/edit' => 'customers#edit'
    get '/customers/confirm_withdraw' => 'customers#confirm_withdraw'
    patch '/customers/information' => 'customers#update'
    patch '/customers/withdraw' => 'customers#withdraw'
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete 'destroy_all'
      end
    end
    get '/orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :index, :show, :create]
    post '/orders/confirm' => 'orders#confirm'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders

  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customer = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customer_path(customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row m-3">
    <div class="col offset-md-2">
      <h4><%= @customer.first_name %><%= @customer.last_name %>さんの会員情報編集</h4>
    </div>
  </div>
  <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
  <div class="justify-content-center">
    <table class="table table-borderless">
      <tr>
        <th>会員ID</th>
        <td><%= @customer.id %></td>
        <td></td>
      </tr>
        <th>氏名</th>
        <td><%= f.text_field :first_name %></td>
        <td><%= f.text_field :last_name %></td>
      <tr>
      <tr>
        <th>フリガナ</th>
        <td><%= f.text_field :first_name_kana %></td>
        <td><%= f.text_field :last_name_kana %></td>
      <tr>
      <tr>
        <th>郵便番号</th>
        <td><%= f.text_field :postal_code %></td>
        <td></td>
      </tr>
      <tr>
        <th>住所</th>
        <td colspan="2"><%= f.text_field :address %></td>
        <td></td>
      </tr>
      <tr>
        <th>電話番号</th>
        <td><%= f.text_field :telephone_number %></td>
        <td></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= f.email_field :email, autofocus: true, autocomplete: "email" %></td>
        <td></td>
      </tr>
      <tr>
        <th>会員ステータス</th>
        <td>
          <%= f.radio_button :is_deleted, :false %>
          <%= f.label :is_deleted, "有効" %>
          <%= f.radio_button :is_deleted, :true %>
          <%= f.label :is_deleted, "退会" %>
        </td>
      </tr>
    </table>
  </div>

  <div class="actions offset-md-3">
    <%= f.submit "変更を保存", class:"btn btn-lg btn-success" %>
  </div>
<% end %>

</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row m-3">
    <div class="col offset-md-2">
      <h4>会員一覧</h4>
    </div>
  </div>

  <table class="table">
    <thead class="table-dark">
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customer.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= link_to admin_customer_path(customer.id) do %>
          <%= customer.first_name %> <%= customer.last_name %>
          <% end %>
        </td>
        <td><%= customer.email %></td>
        <td>
          <% if customer.is_deleted == false %>
            <span>
              <p>有効</p>
            </span>
          <% elsif%>
            <span>
              <p>退会</p>
            </span>          
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="row">
    <div class="mx-auto">
      <%= paginate @customer%>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row m-3">
    <div class="col offset-md-2">
      <h4><%= @customer.first_name %><%= @customer.last_name %>さんの会員詳細</h4>
    </div>
  </div>

  <table class="table table-borderless">
    <tr>
      <th>会員ID</th>
      <td><%= @customer.id %></td>
    </tr>
    <tr>
      <th>氏名</th>
      <td><%= @customer.first_name %></td>
      <td><%= @customer.last_name %></td>
    </tr>
    <tr>
      <th>フリガナ</th>
      <td><%= @customer.first_name_kana %></td>
      <td><%= @customer.last_name_kana %></td>
    </tr>
    <tr>
      <th>郵便番号</th>
      <td><%= @customer.postal_code %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td><%= @customer.address %></td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td><%= @customer.telephone_number %></td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td><%= @customer.email %></td>
    </tr>
    <tr>
      <th>会員ステータス</th>
      <td>
        <% if @customer.is_deleted %>
          <span>
            <p>退会</p>
          </span>
        <% elsif %>
          <span>
            <p>有効</p>
          </span>
        <% end %>
      </td>
    </tr>
  </table>
  <div class="row justify-content-md-center">
    <div class="col-2">
      <%= link_to edit_admin_customer_path(@customer.id) do %>
        <button type="button" class="btn btn-success">編集</button>
      <% end %>
    </div>
    <div class="col-3">
      <%= link_to admin_path do %>
        <button type="button" class="btn btn-primary">注文履歴一覧を見る</button>
      <% end %>
    </div>
  </div>
</div>